name = "rough-haze-94cf"
type = "webpack"
workers_dev = true
account_id = "d98558ced0d40d7099ddb370a9bfa3be"
zone_id = "a213346d81b4f8251343733e62ede213"
kv_namespaces = [
    { binding = "BUCKET",   id = "ba5cd28dc76e4917b75a80a37bed1f81" }
]

[env.staging]
name = "drive-staging"
